### ISSUE TITLE
Storage Drawers Void Upgrade

### ISSUE THREAD

**Issue by zOwenn** [davqvist/Exoria#100]
I feel that the recipe for the Void Drawer Upgrade is slightly expensive due to the limited supply of obsidian (a bit extensive to get enough, better used elsewhere etc). And as the void upgrade is more of a quality of life upgrade and necessary in some cases (I dont want to flood the server with excess phosphor etc :P). Maybe consider making this recipe cheaper?

**Comment by zOwenn** [comment]
Maybe make it use a bucket of lava or something? I mean, there's plenty of that around :P

**Comment by davqvist** [comment]
Bucket of Lava is annoying to craft in multiples. How about I make it 2 Obsidian instead of 8?

**Comment by zOwenn** [comment]
Yeah, that sounds better - lava was just a suggestion (a poor one at that heh)

**Comment by davqvist** [comment]
Fixed in 0.4.0
