### ISSUE TITLE
Life Infuser Bucket Dupe bug. 

### ISSUE THREAD

**Issue by Dystilled** [davqvist/Exoria#105]
Easily replica-table

Life Infuser reciper: 1 Fish (any type) + 1 Water bucket + 1  Sandstone Infusion stone. 
As soon as the recipe begins processing it outputs 1 empty bucket in the Input slot. 
When the processing ends it outputs a "Bucket with ....." 
Placing the fish into a fish tank also gives an empty bucket, duping the initial bucket.

**Comment by davqvist** [comment]
I changed the recipes to empty buckets and leave it like that.
