### ISSUE TITLE
Structured Crafter is not craftable (Quest: Basic Autocrafting)

### ISSUE THREAD

**Issue by Dystilled** [davqvist/Exoria#106]
Structured Crafter requires 
1x TiC - Crafting Station
1x Applied Energistics 2 - Wooden Gear

Recipe for Wooden Gear is 4 sticks in a diamond shape, this is the same recipe as Buildcraft Wood Gear. 

The BC recipe takes precedent so the AE2 one is uncraftable. 

AE2 recipe needs changing (i.e 5 sticks in a +) or Structured Crafter needs to be changed to accept BC gears.

**Comment by davqvist** [comment]
Fixed in 0.4.0
