### ISSUE TITLE
Bane of Trees deletes logs

### ISSUE THREAD

**Issue by davqvist** [davqvist/Exoria#118]
Maybe because wood has Mining Level?

**Comment by Pandemoneus** [comment]
Tried to fix it on my own, simply increasing the mining level of the lumber axe to iron sadly did not fix this.

**Comment by Pandemoneus** [comment]
As discussed in Discord, the flag in primal.cfg to disable the requirement for correct tools to harvest logs is called B:HARVEST_LOGS_REQUIRE_TOOLS

**Comment by davqvist** [comment]
Fixed in 0.4.1
