### ISSUE TITLE
[Suggestion] Remove restriction on placing block and only restrict using block

### ISSUE THREAD

**Issue by superfluke** [davqvist/Exoria#125]
The way the block is put back into inventory seem to cause problems. Since blocks are prevented from being used, I think removing the restriction on placing things like the furnace wouldn't change progression and would avoid a few inventory bugs.

**Comment by davqvist** [comment]
I will fix hopefully placing blocks making issues, but I need prevent placing as you could interact with hoppers and circumvent the restriction.
