### ISSUE TITLE
[Suggestion] Swap 'Resource Automation' and 'Magical Life' quest lines

### ISSUE THREAD

**Issue by Pandemoneus** [davqvist/Exoria#127]
As far as I can see the 'Resource Automation' is the following quest line to 'Survival', whereas 'Magical Life' is even later (or something optional). Therefor, I suggest swapping the quest lines so the quest flow follows the logical progression.

**Comment by davqvist** [comment]
Magical Life is parallel to multiple quest lines. It doesn't "fit" anywhere perfectly. To me it makes the most sense that it is ordered in line when it opens up which is in second place.
