### ISSUE TITLE
Crash when clicking on empty space in Better Questing book

### ISSUE THREAD

**Issue by ChiefLogan3010** [davqvist/Exoria#13]
[crash-2017-10-08_15.43.39-server.txt](https://github.com/davqvist/Exoria/files/1366965/crash-2017-10-08_15.43.39-server.txt)

Happened when i accidentally clicked on the empty space in the middle of the book on the first quest.

**Comment by davqvist** [comment]
On the Checkbox Button? Or what empty space?

**Comment by ChiefLogan3010** [comment]
Was unable to replicate so could just be a coincedence with the click being the same time as the crash. It was between the checkbox and the 'binder' part of the book.

**Comment by davqvist** [comment]
Can't replicate, sorry. Let me know if it happens again or have more info as the log was not really helpful, unfortunately.
