### ISSUE TITLE
Item Vacuum from Embers Ignores Floor

### ISSUE THREAD

**Issue by thaimichael** [davqvist/Exoria#138]
Doubt if anything can be done but Item vacuum from embers mod affects items in the room below tested this with ash block, wood blocks, and diorite blocks.  Items will not pass through the ceiling but will get sucked across room and fall on the floor below the item vacuum.

**Comment by davqvist** [comment]
Well that is just how the Vacuum works, doesn't the Actually Additions or the EnderIO Vacuum work the same way? I can't remember. The "Magnet" just doesn't check if there is a path to itself as this would be hard to do. I'm closing this issue
