### ISSUE TITLE
[Suggestion] Set drop chance for flaking to 100%, but reduce possible amount of flaked items

### ISSUE THREAD

**Issue by Pandemoneus** [davqvist/Exoria#139]
I find the RNG mechanic for flaking diamonds to be annoying. RNG mechanics can be fun, but in this case it isn't. You can't tell how many diamonds you will need to farm to be able to craft the diamond pickaxe or diamond-stiffened mesh.
Right now the chance for each flaked diamond to drop is 45%, with 3 possible drops total. Flaked diamond points then again have 45% chance to drop, but only with 2 drops.

Therefore, my suggestion is to change the drop rate to 100%, but change the drop amount from diamonds to flakes to 1, and from flakes to pointy flakes to 2. For a diamond stiffended mesh you will need 4 diamonds then. Same for a diamond pickaxe.
The same should be applied to all other flaking items. I am aware that this is a buff, but I think it makes this crafting step more satisfying.

**Comment by davqvist** [comment]
I can find `D:FLAKE_CHANCE_GEM=0.45` in the configs, but I can't find the amount of rolls / max amount of flaked items you get. Where did you see that?

**Comment by Pandemoneus** [comment]
Ingame, via JEI. It says "In world flaking", and then diamond -> 3 flakes, and another recipe is diamond flake -> 2 pointy flakes. No idea whether you can change that with CT.

**Comment by davqvist** [comment]
Ah, no I can't change that then. Will leave it for now as-is.
