### ISSUE TITLE
No way to get primalcore lit torch for 'fire me up' quest

### ISSUE THREAD

**Issue by ChiefLogan3010** [davqvist/Exoria#14]
When you sneak-right click as the tooltip on the un-lit torch says, it gives you a vanilla torch which then disappears when trying to place it.

**Comment by davqvist** [comment]
Sneak right click on the lit torch right?

**Comment by ChiefLogan3010** [comment]
Yep, when I do that it gives a vanilla torch rather than a primal lit torch.

**Comment by DJJBanx** [comment]
It does work.

**Comment by davqvist** [comment]
Right click with unlit torch on lit torch to light them.
Still weird that you get a vanilla one.
I will investigate

**Comment by weedgoku** [comment]
This issue is still not fixed.

**Comment by davqvist** [comment]
I know, that is why the issue is still open. Do what I wrote above though

**Comment by davqvist** [comment]
Will be fixed in 1.3.0
