### ISSUE TITLE
Iron rod inconsistency

### ISSUE THREAD

**Issue by Pandemoneus** [davqvist/Exoria#140]
Currently there are three ways to make iron rods:
Form iron rods from Immersive Engineering in a rod mold, this costs 1/2 iron ingots per rod.
Craft iron rods from Vulpes Lib, this costs 3/4 iron ingots per rod.
Craft iron sticks(!) from Futurepack, this costs 1/4 iron ingots per rod.

**Comment by davqvist** [comment]
Removed Oredict from Iron Sticks and removed crafting recipes from all rods
