### ISSUE TITLE
Can't turn off waypoints

### ISSUE THREAD

**Issue by ChosenArchitect** [davqvist/Exoria#144]
When I turn waypoints off and close they come back and are back on again

**Comment by redcatone** [comment]
https://github.com/TeamJM/journeymap/issues/15

Seems to be an issue with 5.6.0. They suggest downgrading to 5.5.2 as 5.6.0 is not publicly available anymore.

**Comment by davqvist** [comment]
Downgraded Journeymap in 0.4.3
