### ISSUE TITLE
Update Misty world, then allow vanilla saplings to be grown there

### ISSUE THREAD

**Issue by Pandemoneus** [davqvist/Exoria#145]
The alpha_c update adds a config setting that can change whether vanilla saplings can be grown in the Misty world (right now they can't be).
If the player decides to move his/her base into the dim, he should also be able to grow vanilla trees there.

**Comment by Pandemoneus** [comment]
Note, should you update, I suggest the following config changes:
The first change prevents any accidental placement of campfires using vanilla stones.
```
    S:stoneAndColors <
     >
```
The second change allows the growth of vanilla trees in the Misty World.
```   
    B:disableVanillaTreeGrowth=false
```
Also note that the update adds Lapis Ore to the Misty world, which you should disable.

**Comment by davqvist** [comment]
Done in 0.4.3, I didn't update to the latest Misty World with the Lapis Ore yet though, will do at later point.
