### ISSUE TITLE
Unusable recipes

### ISSUE THREAD

**Issue by lynaevm** [davqvist/Exoria#146]
recipes exist in JEI for torches that are only coal or charcoal.  The recipe doesn't work nor does it appear intended.

The terraqueous wood door recipe also has a conflict.  It defaults to 1 oak door, but can also make 2 colored doors when you can select the recipe in a forestry workstation.

**Comment by davqvist** [comment]
Removed the bugged torch recipes in 0.4.3.
I can't replicate the Wooden Door issue, it seems like a mod update for 0.4.3 fixed it.
