### ISSUE TITLE
Flexible Sword Image

### ISSUE THREAD

**Issue by lynaevm** [davqvist/Exoria#147]
the flexible sword currently shows the image of... some sort of advanced rocketry control panel?  The name and stats show correctly, but the Flexible Tools quest doesn't complete.

**Comment by Pandemoneus** [comment]
Duplicate: https://github.com/davqvist/Exoria/issues/122
However, that the sword is not recognized by the quest is a new issue.

**Comment by Pandemoneus** [comment]
The quest just randomly completed for me. The sword is at about 90% durability.

**Comment by davqvist** [comment]
I should have fixed the detection in 0.4.3
