### ISSUE TITLE
Sky Resources 2 Crucible is not accepting leaves to be turned into water

### ISSUE THREAD

**Issue by ChosenArchitect** [davqvist/Exoria#149]

**Comment by davqvist** [comment]
Are you sure? You have to throw them in, not right clicking or anything.

**Comment by ChosenArchitect** [comment]
Sorry, wasn't clear lol I just made the wooden one... I forgot how SkyRe works... derp... You can use the wooden crucible to get water as well so thats what I did.

**Comment by ChosenArchitect** [comment]
Maybe change this to suggestions - add (drop the leaves into the crucible) into the text. If I have will save you a headache later on when its released

**Comment by davqvist** [comment]
Added a line into the quest book in 0.4.3
