### ISSUE TITLE
Oredict aluminum in duraluminum recipe in Compound Maker

### ISSUE THREAD

**Issue by Pandemoneus** [davqvist/Exoria#152]

**Comment by davqvist** [comment]
I can't OreDict it, machine doesn't allow it. I might add a recipe for every Aluminum Ingot, Just out of curiousity, which Aluminum Ingot did you have which wasn't allowed? I ask because you shouldn't be able to get an Aluminum Ingot from another mod.

**Comment by Pandemoneus** [comment]
MagneticCraft aluminum when you cast molten alu.

**Comment by davqvist** [comment]
I changed it so that you get TE Aluminum Ingots from the Metal Caster now
