### ISSUE TITLE
Flexible Tools: Crash when trying to bind Pickaxvel to diamond chest

### ISSUE THREAD

**Issue by Pandemoneus** [davqvist/Exoria#153]
When you try to bind the pickaxvel to a diamond chest, the client crashes. Already reported this issue to the mod author: https://github.com/MrRiegel/Tools/issues/21

**Comment by Pandemoneus** [comment]
Author updated the mod to fix this crash.

**Comment by davqvist** [comment]
I didn't test, but I updated the mod, so I will close for now
