### ISSUE TITLE
Crafting a resonating wand requires a resonating wand

### ISSUE THREAD

**Issue by Pandemoneus** [davqvist/Exoria#154]
Which came first?
You can't craft one in one of the Astral Sorcery temples because the vanilla crafting table has a changed crafting mechanic. You can't craft a wand in a luminous crafting table because that requires a wand.

**Comment by Pandemoneus** [comment]
Nevermind, just saw that you get one from a quest. However, I would still change the recipe to use the normal crafting table in case the player loses the one from the quest.

**Comment by davqvist** [comment]
Added a Crafting Table recipe
