### ISSUE TITLE
Tiny improvements 

### ISSUE THREAD

**Issue by superfluke** [davqvist/Exoria#157]
Just a few small things that would be nice.

Earth works wicker uses minecraft:stick rather than the stick ore dict
Embers codex can't be placed into biblio craft bookshelf
Wheat seeds (regular vanilla seeds) don't melt into seed oil

**Comment by davqvist** [comment]
1.) Done
2.) Added
3.) Can't replicate, works for me

**Comment by davqvist** [comment]
Closing now as I can't replicate 3.)
If you have more info, let me know and I reopen
