### ISSUE TITLE
PrimalCore barrels not retaining liquids when placed.

### ISSUE THREAD

**Issue by redcatone** [davqvist/Exoria#160]
When using a barrel lid on a barrel, it should let the barrel keep its contents when broken ([wiki page](https://github.com/An-Sar/PrimalCore/wiki/Barrels)).  The barrel will have receive nbt tags as seen here:
![image](https://user-images.githubusercontent.com/24564581/39670168-5bb7ec34-5131-11e8-815f-41d8e360e16a.png)
But upon placing the barrel, all contents inside will be lost.

Exoria: 0.4.2
PrimalCore: 0.6.47

**Comment by davqvist** [comment]
You need to shift right click the barrel on its side to pick it up, then it keeps its contents.

**Comment by redcatone** [comment]
I did as seen in the screenshot, but when placing the resulting barrel back into the world all contents inside are lost.

**Comment by davqvist** [comment]
Sorry can't replicate. Make sure to not break with Axe, you need to shift right click on the side while having a lid on top. Then you can place it again without losing its contents.
