### ISSUE TITLE
Flexible Sword in JEI and in Quest Book Are Using AR Texture

### ISSUE THREAD

**Issue by ChosenArchitect** [davqvist/Exoria#165]
![2018-05-09_21 06 37](https://user-images.githubusercontent.com/35053440/39848532-108b1558-53cd-11e8-8bb4-0d2f33b9adf9.png)
![2018-05-09_21 07 10](https://user-images.githubusercontent.com/35053440/39848533-109dfd1c-53cd-11e8-9d50-ff5eec5379a0.png)

**Comment by davqvist** [comment]
Duplicate to https://github.com/davqvist/Exoria/issues/122
