### ISSUE TITLE
Can't Craft The Flexible Axe

### ISSUE THREAD

**Issue by ChosenArchitect** [davqvist/Exoria#166]
![2018-05-09_22 12 36](https://user-images.githubusercontent.com/35053440/39850289-1756db0c-53d6-11e8-8d54-9f3d15ecbf31.png)

**Comment by davqvist** [comment]
Duplicate to https://github.com/davqvist/Exoria/issues/104, I have no clue why it sometimes doesn't craft, the recipe is correct.
