### ISSUE TITLE
Exoria Underground 

### ISSUE THREAD

**Issue by ChosenArchitect** [davqvist/Exoria#169]
Mobs Are not spawning for my world. I am only seeing Vex and Shulkers and they are really rare to see. I have been in the dim for over an hour and haven't seen anything else.

**Comment by davqvist** [comment]
I have shortly answered you on Discord, but let me elaborate a bit.

This isn't a combat focused pack. Enemy rates are set intentionally to low, this doesn't really matter as the only mob you HAVE to fight are Golems. They are set to a higher spawn rate to any other mob and spawn in all 3 Exoria Dimensions: Exoria, Exoria Underground and Exoria Core. So finding these shouldn't be hard although I agree that you have to spend some time of course. Different mobs spawn at different y levels, Golems spawn below y level 80 so you might have searched too high. I told in the quest that you have to go to the lower levels, although I admit that I can make that clearer and I will do so.

**Comment by davqvist** [comment]
I will increase the spawn rate a bit and make it clear in the quest book that they spawn more closer to bedrock.
