### ISSUE TITLE
Thermal Foundation Bronze Ingot not working on magneticraft crushing table

### ISSUE THREAD

**Issue by thaimichael** [davqvist/Exoria#170]
As I recall the ingot I have is from the embers stamp press, but it is showing as the thermal foundation Bronze Ingot (#4753/163).  When placed upon the crushing table does not appear to have a recipe to create a bronze plate.

**Comment by thaimichael** [comment]
Also, the Electrum ingot made in embers will not process on the crushing table.

**Comment by davqvist** [comment]
Fixed in 1.0.0
