### ISSUE TITLE
Embers Melter Alloying Issues

### ISSUE THREAD

**Issue by thaimichael** [davqvist/Exoria#171]
1. Using processed ingots functioned correctly for gold and copper to Molten Copper and Molden Gold
2. Using Blocks melted but resulted in Liquid Copper and Liquid gold.  Block melting recipes appear missing. To create dawnstone alloy requires Molten Gold + Molten Copper, Liquid Copper and Liquid Gold does not work.
3. Cannot directly melt the ores in melter though you can melt oreberries.

Melting nuggets/ingots/blocks appear to take the same length of time when processing many blocks of bronze was advantageous to use blocks.

**Comment by davqvist** [comment]
Hopefully fixed in 1.0.0
