### ISSUE TITLE
Portal lag when zoning into a dimension

### ISSUE THREAD

**Issue by thaimichael** [davqvist/Exoria#177]
Whenever you zone into a dimension there are couple seconds of lag anything you do during that time does not register.  After a couple of seconds, the area resets you are back at the portal and everything works as expected.  Unfortunately during this lag time if a hostile mob is there it can damage you but you cannot affect it.  It says in the infobox in red "waiting for server"

**Comment by davqvist** [comment]
Nothing I can do, really. Will close this
