### ISSUE TITLE
[Crash report] Crafting table

### ISSUE THREAD

**Issue by sasss20** [davqvist/Exoria#179]
While i put the planks on 2x2 grid to craft a crafting table the game crashed!
Crash report:
{The game crashed whilst rendering ingredient
The game crashed whilst rendering ingredient
Error: java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to net.minecraft.item.ItemBlock}

What i can do?
thanks

**Comment by davqvist** [comment]
Duplicate to https://github.com/davqvist/Exoria/issues/173

**Comment by davqvist** [comment]
Disable C&B for now if you want
