### ISSUE TITLE
Crafting Knowledge unlock didn't work

### ISSUE THREAD

**Issue by staticlando** [davqvist/Exoria#180]
I believe getting the Crafting Knowledge unlock notification should unlock sieves and the crafting station (among other things). Currently I can place the ingredients using the auto placement from the recipe, but then when I click the item it is not created and my ingredients remain on the table.

I uploaded a video showing the issue.

[Broken Crafting.zip](https://github.com/davqvist/Exoria/files/2007423/Broken.Crafting.zip)

**Comment by PrincessOfEvil** [comment]
What did you do to fix this though?

**Comment by davqvist** [comment]
Use your 2x2 crafting grid to craft the crafting station.
