### ISSUE TITLE
[Suggestion] Item Zoom Mod

### ISSUE THREAD

**Issue by redcatone** [davqvist/Exoria#181]
Provides a large preview when hovering over blocks. Great for visualizing small details in blocks, especially darker ones where they are harder to distinguish. Has options to toggle size and visibility.

https://minecraft.curseforge.com/projects/itemzoom
![image](http://i.imgur.com/O5l9byo.png)

**Comment by davqvist** [comment]
Not a big fan, I don't see the big benefit it would provide.

**Comment by redcatone** [comment]
It's true its a personal preference thing. Given that its client-side only, its easy to just drop the mod in when I play. I thought it might be useful to include by default, could be hidden by default, given there is slightly more emphasis on building with restrictions, and how some early game blocks you have access to, such as basalt, are very dark, making it hard to see the details in the different chisel variants.

**Comment by redcatone** [comment]
Vazkii just released a pretty neat mod that allows you to set optional mods for modpacks, which seems great for stuff like this which is more of a personal preference.

https://www.reddit.com/r/feedthebeast/comments/8l4ovr/new_mod_players_choice_read_info_in_comments/

I'll copy paste the comment Vazkii made about the mod.

> Had a bit of downtime so I did this because I had the idea for it in Wyld's stream the day before.

> Transcription of the CurseForge Description:

>> This mod allows modpack devs to ship optional mods and mods that are disabled by default, much like the launchers of modpacks in the old days, like the original Yogbox.
>> 
>>  
>> 
>> Check out the
> 
>> ## [Demo Video](https://www.youtube.com/watch?v=DSZsRE0bL1o)
> 
>> for what it's all about.
>> 
>>  
>> 
>> To configure the mod, simply find the playerschoice.json file in your config folder. The mods the player chooses are saved to the fmlModState.properties file, in the same folder. This mod is in reality just a wrapper for an underutilized forge feature.
>> 
>>  
>> 
>> When shipping the modpack, include fmlModState.properties so that the contents match the default mods you defined in your playerschoice.json file. Do not ship playerschoice.marker in the instance folder. If you want to test your setup, delete playerschoice.marker.

>If you don't feel like watching a video, ![here's a screenshot](https://i.imgur.com/A9MDdF7.png) of what it looks like.

>It'll be available for download [here](https://minecraft.curseforge.com/projects/players-choice) when it's done being approved.
