### ISSUE TITLE
[Suggestion] VanillaFix Mod

### ISSUE THREAD

**Issue by redcatone** [davqvist/Exoria#182]
A relatively new general technical performance enhancer mod. Has a lot of features so it's best to just read the curseforge page for a description of what it does. For the average player the biggest benefit would probably be the way it changes how crashes are handled. Instead of crashing the client it only crashes the world booting you to the title screen.

https://minecraft.curseforge.com/projects/vanillafix

**Comment by davqvist** [comment]
Good idea, added to 1.0.1

**Comment by redcatone** [comment]
I should mention there are a couple issues with the latest curseforge release (1.0.3-30), but they are fixed in [development](https://github.com/DimensionalDevelopment/VanillaFix/issues?q=is%3Aissue+is%3Aclosed). Probably worth holding out till the next version gets released.

I would also recommend setting the config to `LOG` rather than `WARN` as the way Simply Jetpacks 2 does the configs will cause the error to pop up quite a bit which can get annoying during playing.

**Comment by davqvist** [comment]
I wanted to just come here to say it crashes me, I will wait a bit.

**Comment by redcatone** [comment]
Update out (1.0.4-35)

https://minecraft.curseforge.com/projects/vanillafix/files/2562712
