### ISSUE TITLE
Shift clicking to put stuff in a chest causes a crash.

### ISSUE THREAD

**Issue by Ryliia** [davqvist/Exoria#183]
Tried to shift click a item into a vanilla chest and it caused my game to crash with the error "The game crashed whilst rendering ingredient. Error: java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to net.minecraft.item.ItemBlock"

Tried to see if it was maybe just that item that did it, but every item I try to shift+click into a chest does this.

Crash Log https://pastebin.com/QqLg8SkL

**Comment by davqvist** [comment]
Duplicate to  https://github.com/davqvist/Exoria/issues/173, disable Chisel & Bits temporarily if you are in Singleplayer. Searching for something different in JEI also makes it not happen as it happens when you search for specific items.
