### ISSUE TITLE
Getting a torch from a lit torch

### ISSUE THREAD

**Issue by MrTubzy456** [davqvist/Exoria#184]
forge version:: 14.23.3.2688
primalcore version: 0.6.51

You can get a minecraft torch from an unlit torch by placing down an unlit torch and lighting it and then shift + right clicking it. I've posted  an issue on Primalcore's github here :https://github.com/An-Sar/PrimalCore/issues/201 but, I wanted to let you know it was an issue.

**Comment by davqvist** [comment]
Duplicate to https://github.com/davqvist/Exoria/issues/14
