### ISSUE TITLE
"Water" quest is misleading

### ISSUE THREAD

**Issue by McFrugal** [davqvist/Exoria#186]
The text says to use a crucible to turn loam or terra clay into true clay, but you really need a stone barrel.  The directions are backwards as well, since you need to place water in before the block.  Lastly, the quest makes you craft a wooden barrel despite no mention of it in the text.

**Comment by kevsgrove** [comment]
The wooden barrel does work to turn the clay into vanilla clay, stone is not necessary.

**Comment by McFrugal** [comment]
So it just doesn't show up in JEI then?  JEI says a stone barrel specifically is required.

**Comment by kevsgrove** [comment]
Yes, I believe stone is only necessary for dealing with lava/other hot fluids

**Comment by davqvist** [comment]
It was fixed in 1.0.1
