### ISSUE TITLE
Pack crashes on loadup

### ISSUE THREAD

**Issue by coledracon** [davqvist/Exoria#188]
Pack crashes when trying to initially start it. All other modpacks work fine. Tried uninstalling and reinstalling pack and it still crashes.

**Comment by redcatone** [comment]
Without any more info there's not much anyone can do. Paste the crash report somewhere like [hastebin](https://hastebin.com/) then copy the link here.

**Comment by coledracon** [comment]
I am thinking it was an issue with the twitch app. It seems to be working now.
