### ISSUE TITLE
carry on not picking up any whitelisted items

### ISSUE THREAD

**Issue by foxdarts** [davqvist/Exoria#191]
have never been able to pick up any of the white listed items on the carry on list and now that i have advanced into vanilla chests moving the old chests without breaking them would be good.

**Comment by redcatone** [comment]
The default hotkey for Carry On is shift, which can conflict with other stuff. I recommend changing it. For example, I set mine to use the `left alt` key.

**Comment by davqvist** [comment]
You also need to stand close to the block you want to carry, otherwise it won't work.

**Comment by foxdarts** [comment]
got it. ya it was bound weird. working fine now.
