### ISSUE TITLE
Fast Leaf Decay

### ISSUE THREAD

**Issue by SephirothWS** [davqvist/Exoria#194]
I don't know why your packs don't have it, but I highly dislike having to wait for leaves to decay normally. Can we have fast leaf decay added to the pack by any chance?

**Comment by davqvist** [comment]
No, it is intentional for several reasons. 
1.) You often want the leaves to shear and this is easier without Fast Leaf Decay
2.) Raid a Botania Building for the Horn of the Canopy which resolves this issue or
3.) Get a Bane of Leaves early game which as well resolves this problem

**Comment by SephirothWS** [comment]
And just how early game is obsidian for hardened stone?

**Comment by davqvist** [comment]
You will see, as soon as you have a furnace basically.
