### ISSUE TITLE
[BUG?] Cannot craft Bee Houses in normal Crafting Table

### ISSUE THREAD

**Issue by hron84** [davqvist/Exoria#200]
I already unlocked `bee_knowledge` stage and also I have the "To bee or not to bee" quest, but cannot craft Bee Houses. See attached screenshot. I cheated in a Crafting Station, in that stuff Bee Houses is craftable. However, in this stage, I do not have a recipe for the Station. 

![2018-05-19_06 28 42](https://user-images.githubusercontent.com/88636/40264931-6ef28e9c-5b2e-11e8-81e0-5f525cc3983b.png)

**Comment by davqvist** [comment]
Known bug, you have to wait until you have the Tinkers Crafting Station.

**Comment by hron84** [comment]
To be honest, I kept the cheated Crafting Station because I did not feel it to break my progression but the another bench is too annoying for me. PrimalTech's crafting stump is way more better...

**Comment by davqvist** [comment]
Finally fixed in 1.3.0
