### ISSUE TITLE
shift clicking causeing crash

### ISSUE THREAD

**Issue by foxdarts** [davqvist/Exoria#203]
[crash-2018-05-19_14.13.58-client.txt](https://github.com/davqvist/Exoria/files/2019719/crash-2018-05-19_14.13.58-client.txt)
shift clicking anything from any inventory to another results in a crash

**Comment by miner-bob-1960** [comment]
Same here, was fine to start then just started crashing on shift click
[crash-2018-05-21_16.06.59-client.txt](https://github.com/davqvist/Exoria/files/2023105/crash-2018-05-21_16.06.59-client.txt)


was fine after full reinstall

**Comment by KingofThemyscira** [comment]
Shift clicking any item in the inventory is crashing the game to include shift clicking in the 2x2 crafting grid.

**Comment by davqvist** [comment]
This is fixed in 1.0.2
