### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by alio314** [davqvist/Exoria#204]
Any idea why this is happening?

![ezgif com-optimize](https://user-images.githubusercontent.com/39442868/40271767-ffe4e102-5b6f-11e8-84ca-b56c45961085.gif)

**Comment by davqvist** [comment]
Yes, you changed your BetterFPS settings.

**Comment by NerdySpider** [comment]
did you turn seizure mode on?
jokes, but seriously that might be from betterFPS

**Comment by davqvist** [comment]
Closing this, I hope you figured it out
