### ISSUE TITLE
Can't apply Gold Tier Upgrade to Yabba Barrels

### ISSUE THREAD

**Issue by Coolfox24** [davqvist/Exoria#206]
Gold tier upgrade won't apply to any Yabba Barrel.

Tried multiple barrels, empty/full, with no success, haven't tried other storage upgrade upgrades, however the void upgrade applied to the barrel with no issues.

**Comment by davqvist** [comment]
Yabba Barrel Upgrades need to be applied in order, not sure if you did that, but you need to apply a Tin Upgrade first.

**Comment by davqvist** [comment]
Closing this issue, post here if you have still this issue
