### ISSUE TITLE
Bane of ... Ash?

### ISSUE THREAD

**Issue by SephirothWS** [davqvist/Exoria#210]
Going through countless stone & iron shovels digging out an underground base... I like how there's a Bane of Cobble that works well on the basalt in the world, can we get a similar equivalent for the large amount of ash blocks in the world?

**Comment by PrincessOfEvil** [comment]
Like the Excavators?

**Comment by SephirothWS** [comment]
Not an excavator. Just an unbreakable shovel usable only on stuff like dirt, ash, etc.

**Comment by davqvist** [comment]
Yeah just use an Excavator as I can't add a Bane of Ash, sorry.

**Comment by SephirothWS** [comment]
@davqvist How would I get an excavator then?

**Comment by PrincessOfEvil** [comment]
Hammer crafting table.
