### ISSUE TITLE
Embers' Mixer Centrifuge cannot make Electrum from liquid silver and gold from different mods

### ISSUE THREAD

**Issue by querns** [davqvist/Exoria#211]
When attempting to make electrum, I used the Embers melter to melt gold nuggets and Survivalist silver ore rocks. The Melter produced Tinker's Construct molten gold and Foundry's liquid silver from these inputs. Once piped into the Mixer Centrifuge, the metals refused to alloy. Looking at JEI, there is a recipe for when both molten metals are from the same mod (both TiCon and Foundry,) but not a recipe for when they are from separate mods.

A resolution would likely require two additional recipes; one for "molten gold" and "liquid silver," and one for "liquid gold" and "molten silver." 

I haven't tried it, but looking at JEI, I suspect that molten bronze and molten dawnstone have similar issues.

**Comment by thaimichael** [comment]
I went through this before and from what I found you first need to process the nuggets in the foundry into either an ingot or block prior to processing in the melter. (use to block did not work but with 1.0+ does)

**Comment by davqvist** [comment]
Yeah I have added recipes with the Molten metals and the Liquid metals but not with one of each. I can add that in an update.

**Comment by davqvist** [comment]
Forgot to close it, but this was fixed in 1.2.0
