### ISSUE TITLE
Game Crash upon world load

### ISSUE THREAD

**Issue by Andr0oS** [davqvist/Exoria#214]
Something (I won't say what for sure) caused my whole computer to crash while I was playing Exoria, but now every time I load the world I get this error:
https://paste.dimdev.org/ezumidivez.txt

**Comment by davqvist** [comment]
Your computer crash must have corrupted something, not sure what exactly either as I can't find the described BCMod-Items.dat in my instance. I think you have to load a backup.

**Comment by Andr0oS** [comment]
Alright, I'll probably just start a new world since I was only a few hours into it... and I remember the seed I used. :P

**Comment by davqvist** [comment]
Closing this as I have no clue what was going on there
