### ISSUE TITLE
Cannot fill Watering Can through crafting + Watering Can duplication

### ISSUE THREAD

**Issue by CanvasK** [davqvist/Exoria#215]
Attempting to fill the Thermal Cultivation Watering Can (basic) with the Water Bucket + Watering Can recipe does not fill the Watering Can, but uses up the water in the Water Bucket. Bucket is kept and so is the Watering Can in the crafting grid, but a new Watering Can is made in the output slot.

Recipe appears to be shared with higher tier watering cans, so duplication of them may be possible if it is the same; I cannot test this as I'm not at that tech level.

Since they can not be uncrafted or smelted into other resources, I'm not 100% sure if this is intentional or not. But does not seem to have a big impact other than voiding water.

How to replicate: Craft a Watering Can and Water Bucket together (In-hand crafting or crafting table)

**Comment by davqvist** [comment]
I am aware of this and this is fixed in dev of the mod, just waiting for an update.

**Comment by davqvist** [comment]
This was fixed in 1.2.0
