### ISSUE TITLE
Sieve and Hourglass

### ISSUE THREAD

**Issue by JaxxDynasty** [davqvist/Exoria#220]
So I've unlocked the knowledge for the Sieve and the hourglasses but when I place down the materials they won't show the item and if I use the autoplace then It shows the item but it won't allow me to right click to take the item out. Tried restarting my client but the problem remained.

**Comment by redcatone** [comment]
Known issue with the immersive crafting table. For the time being, you have to craft those recipes in something like the Tinkers' crafting station. This quest unlocks the recipe for the crafting station.
![Quest](https://cdn.discordapp.com/attachments/306346221805633537/447765907394265088/unknown.png)

**Comment by JaxxDynasty** [comment]
Alright thank you
