### ISSUE TITLE
Extreme Lag

### ISSUE THREAD

**Issue by CIockworkGhost** [davqvist/Exoria#228]
Hello, I am EliteDuke0491 (same person from on CurseForge). The problem is extreme lag caused by an unknown source on my world. I updated to 1.0.2 recently, and soon after I finished constructing a pipe based storage system for Strainer items. Thereafter, extreme lag occurred. I presumed it was due to the automatic sieve, I managed to disable that. The lag continued. The lag type seems to be Walia (or similar mods) not showing data, blocks not loading (they resemble stars until they load), and the inability to complete actions without waiting two minutes for the action to occur.

**Comment by CIockworkGhost** [comment]
I have returned to the game, and the lag has decreased slightly after the sieve was disabled.

**Comment by davqvist** [comment]
Oh I have just answered you on CurseForge. Same info here: Type "/profile e" and see the results. It should tell you the source of lag. But very likely not caused by an update.

**Comment by NerdySpider** [comment]
@SirJamesGhost have you tried turning particles down to minimal? I have extreme lag when they're on decreased or all. though the moment I set it to minimal it goes to a normal state. this might be from all the ash block particles

**Comment by davqvist** [comment]
Is your issue fixed/solved? Do you need more help?
