### ISSUE TITLE
[1.0.2] Recipe error/bug - Botania Water Rune

### ISSUE THREAD

**Issue by SjetCraft** [davqvist/Exoria#230]
Default Botania Water Rune recipe requires a vanilla Fishing Rod which is disabled by Just a Few Fish causing the Water Rune to be uncraftable.

Recommend using the Wooden Fishing Rod by Just a Few Fish which is gated behind iron due to the hook.

**Comment by davqvist** [comment]
I made both Fishing Rods interchangable in 1.1.0
