### ISSUE TITLE
Possible bug in the process of getting the Exoria Bee

### ISSUE THREAD

**Issue by KingofThemyscira** [davqvist/Exoria#233]
Exoria bee = Rune Princess & Fairy drone
             Rune = Fairy & Rock, rock is easy to get from hot and wet.
The problem is you can't process the rock queen to get a drone or princess because the rock bee's requirements can not be met.  You have to be in Exoria underground but the undeground has no sky view since the highest point is bedrock.  

Am I missing something here cause I can figure out how to process this Rock bee, seems like an oversight maybe?

**Comment by davqvist** [comment]
The Rock Bee can be used in caves (unless you use that trait through breeding). Not sure how far you are in progression, but you can also use the Acclimatizer to be able to use the Rock Bee in the Exoria "Overworld"
