### ISSUE TITLE
Niobium Pickaxe

### ISSUE THREAD

**Issue by Phewsion** [davqvist/Exoria#239]
The Quest "Hard Metals" says you need to make a Niobium pickaxe to get through the hard foggy stone, but the "Hard Foggy Stone" requires Obsidian level mining, and the "Niobium Pickaxe" isn't being recognized as one, you can use the Flexible Pickaxe but it takes so long to mine 1 block your filter coal runs out after maybe 2-3 blocks

![image](https://user-images.githubusercontent.com/37968676/40591451-a185929e-6265-11e8-8cc1-4ed8352dd1d0.png)

**Comment by davqvist** [comment]
Hard Metals is referring to the Foggy Stone at the top layer. Add Haste Upgrades to the Flexible Tool and probably also Range Upgrades to break it faster, you can also make an Exchanger to harvest it even faster. The Filter Coal shouldn't run out that fast though, it should last 10min at least.

**Comment by Phewsion** [comment]
The quest text says "hard foggy stone material" so I assumed it meant the item named "Hard Foggy Stone", I've added 4 haste upgrades to the flexible tool, didn't think about ranged upgrades, and I didn't look for exchangers, to used to better builders wands I think :) Thanks

Filtered Coal ran out in 3 minutes, in that time with an Axpickvel with 4 haste upgrades I got 3 hard foggy stone I didn't put the respirator on till I hit the bottom under mist, went straight to my tunnel, used the warp stone to port out when filtered coal hit 100%, the whole thing took about 3-4 minutes from when I put the respirator on

**Comment by davqvist** [comment]
I reworded the quest a bit in upcoming 1.1.0
