### ISSUE TITLE
Futurepack Research Requiring Bauxite Ore

### ISSUE THREAD

**Issue by ChosenArchitect** [davqvist/Exoria#240]
![2018-05-27_22 14 03](https://user-images.githubusercontent.com/35053440/40595670-aab90ec8-61fb-11e8-8fdc-e112fdc52bd9.png)
![2018-05-27_22 14 11](https://user-images.githubusercontent.com/35053440/40595671-aaca8a90-61fb-11e8-9d63-528e6b0f3885.png)

**Comment by davqvist** [comment]
Yes, I think this one you can't complete, but you don't need it as it teaches you how to process Aluminium but you can do that already.

**Comment by davqvist** [comment]
Thinking more about it, I can probably add a recipe to make Bauxite Ore for completionists in the next update.

**Comment by davqvist** [comment]
Will be added in 1.1.0
