### ISSUE TITLE
Auto sifter ingores restrictions for sieves

### ISSUE THREAD

**Issue by MorganSimic** [davqvist/Exoria#241]
After you place the sieves and the auto sifter and then automatically pipe in stuff into the sifter it will continue to work even when you remove the shakes or open the room.
The player can't interact with the sieves as intended when the requirement is not met.

**Comment by davqvist** [comment]
I mean yes, that is the same with the furnace if you automate with hoppers, that is not really a bug though just a limitation of the system.
