### ISSUE TITLE
TPS drops when you enter the core 

### ISSUE THREAD

**Issue by CRJFELIX** [davqvist/Exoria#242]
Server is at 20 TPS otherwise but as soon as you enter the core it drops to around 4 then as soon as you leave the core it goes back up to 20TPS

**Comment by davqvist** [comment]
Read the "Important Notes" when entering the world. World gen is heavy. I assume you didn't pregen the dimension either. It should go away after a while when the surroundings are fully loaded/genned.

**Comment by CRJFELIX** [comment]
@davqvist So is there a mod or command built into the pack or do we need to add it also is there another way to see important notes because they don't appear when entering the world

**Comment by davqvist** [comment]
You don't see the popup of the Important Notes when you join? It tells you about the lag when creating a new dimension. In any case, the command to pregen would be `/forge generate 0 0 0 10000 1102 100`
meaning it starts at coords 0 0 0, generates 10k chunks in total in dimension 1102 (Exoria Core) and the interval in chat is 100 chunks. You can also add the Chunk Pregenerator mod which does this faster and better, but I don't know its commands well.

**Comment by davqvist** [comment]
Closing this as I can't do anything about it
