### ISSUE TITLE
Refined Storage crafting issues

### ISSUE THREAD

**Issue by mkleiman312** [davqvist/Exoria#243]
Exoria 1.02

1. Refined Storage cannot craft (or autocraft) anything with an unlock requirement (e.g., a Tinker's crafting station).  The recipe shows correctly, but the item disappears when you take it out of the grid.  Not a major issue since you can move the items to an in-world crafting table, but its a minor annoyance.

2. Crafting Actually Additions Greenhouse Glass in a Refined Storage grid crashed my game (server, not client).  Did this twice to confirm the bug.  Same recipe works fine in an in-world crafting table.

**Comment by davqvist** [comment]
1.) Yeah can't do anything about that.
2.) Please hastebin a crash log here.

**Comment by mkleiman312** [comment]
https://pastebin.com/SLwYPH9K

note: useful information starts at line 1438, but I included the full crash-related log for debug purposes
