### ISSUE TITLE
is it intended that players have unlimited mana?

### ISSUE THREAD

**Issue by ImelchorI** [davqvist/Exoria#244]
i just started the pack and didnt get far yet. but giving us two creative mana pools is quite generous.

whats stopping us from picking them up and using them for botania crafting, or just putting a mana spreader next to one of them to get an unlimited supply?

**Comment by McFrugal** [comment]
I wasn't sure if that was intentional either, but a quest later makes it obvious that yes, it is.  You have infinite mana in this pack.

**Comment by davqvist** [comment]
Yes, it is intentional
