### ISSUE TITLE
Logs cannot be inserted into a fluid transposer (for treated wood)

### ISSUE THREAD

**Issue by querns** [davqvist/Exoria#245]
The alternate recipe for treated wood involves using a fluid transposer on a wood log to get treated wood. However, the fluid transposer refuses to accept a wood log as an input. I've tried manually inserting the log, shift-clicking, using pipes, and an attached inventory with auto-input enabled on the fluid transposer, and nothing works.

**Comment by davqvist** [comment]
I don't know why it is not working while it should

**Comment by MorganSimic** [comment]
The same issue exists with planks to lacquer planks with urushi. I changed the script from using a wildcard in the input to just oak planks. so from `minecraft:planks:*` to `minecraft:planks:0` . This fixed the recipe. I wanted to try the same for the Log to Treated Wood recipe but i could not  find the script for that. Maybe i'm just blind. 
So it could be an issue with the using the wildcard for metadata but i'm not versatile enough in craftweaker scripts to confirm that 100%.

**Comment by davqvist** [comment]
Thanks. I will have a look.

**Comment by davqvist** [comment]
Fixed in 1.3.0
