### ISSUE TITLE
Futurepack Research Requiring Magnetite Ore

### ISSUE THREAD

**Issue by ChosenArchitect** [davqvist/Exoria#246]
![2018-05-29_15 14 25](https://user-images.githubusercontent.com/35053440/40683124-282b8e96-6353-11e8-91e1-5f088c798e01.png)
![2018-05-29_15 14 37](https://user-images.githubusercontent.com/35053440/40683125-28402572-6353-11e8-92f1-42fd2f85b844.png)

**Comment by davqvist** [comment]
Yes, you get it from the Void Ore Miner.
