### ISSUE TITLE
the requirement for specific building materials needs changing.

### ISSUE THREAD

**Issue by ImelchorI** [davqvist/Exoria#249]
its really starting to get on my nerves, that we have to build an entire extra room for every little machine were crafting. the worst part is that the materials arent interchangable either.

cant put a vanilla furnace in a concrete room, build an extra room for the sifter, and one for the smelter that definitely cant just be made out of basalt.

it would be fine, if it was a general requirement of outdoors vs. indoors, or if there was at least some flexibility in the building materials (vanilla furnace can go into a room out of concrete and other higher tier materials, and the sifter can go anywhere as long as its indoors etc.).

personally, im not enjoying the restrictions in building materials. i get what youre trying to do with it, adding a bit to the progression, but it doesnt work out very well since it heavily restricts us in how we can lay out our bases.

another thing that stinks about it, is that you cant simply put machines against walls, since they will complain that the required blocks are obstructed. also, there is this weird issue of leaving a door open makes your machines stop working.

**Comment by davqvist** [comment]
Thanks for your feedback, but this is intentional design, if you don't enjoy it, feel free to remove the Restriction mod or play a different pack.
