### ISSUE TITLE
Biofuel Generator is unusable

### ISSUE THREAD

**Issue by MorganSimic** [davqvist/Exoria#250]
The Biofuel Generator from Industrial Foregoing is one of the options for power listed in the 'Power if choice' quest. But to run it you need the Biofuel from IF wich is only obtainable through the Bioreactor that is not craftable at that point due to needing a Fermented Spider Eye. From what i have seen, Spider Eyes are earliest obtainable through Woot. 
So basically the quest offers an option that is not usable. Possible solutions would include removing this option from the quest wich would not hurt that much because alternatives are abundant or changing the recipe for the Bioreactor to not include a Spider Eye or implenting an option for obtaining Spider Eyes earlier.

On a side note, due to the absense of Spider Eyes the Gendustry Lifespan Upgrade and Botanias Rod of the Shifting Crust are gated behind Woot. Just as a notice.

**Comment by mkleiman312** [comment]
AFAIK, everything needed for Tier 1 Woot spawner (including a spider spawner) is available before the "Power of Choice" quest opens.

**Comment by MorganSimic** [comment]
Everthing in Woot is gated behind Stygian Iron and thus the Compound Maker. One could argue that this is feasible to get before the 'Power of Choice' Quest because it only needs the Compact Machine shrinking setup and Signalum alloying. But the quest for Woot is quite a bit further down the questlines so if you don't know Woot exists and what it does you don't see this option because JEI doesn't tell you. And every step to getting Woot and Woot itself require power, so it would make sense to have reliable power setup beforhand.

**Comment by davqvist** [comment]
Thanks for the heads up, will be fixed in 1.1.0
