### ISSUE TITLE
Making stone in foundry uses unexpected mold.

### ISSUE THREAD

**Issue by NiSiSuinegEht** [davqvist/Exoria#252]
Melting down cobblestone in the Melting Crucible to get seared stone, and pouring it into the Metal Caster, you would expect to use the block mold to cast it back into item form, but it uses the plate mold to get stone blocks, instead.  Is this intended to be unintuitive, or the wrong mold selected in the CraftTweaker script?

If so, then the line:

mods.foundry.Casting.addRecipe(<minecraft:stone>, <liquid:stone> * 72, <foundry:mold:1>);

in foundry.zs should instead read:

mods.foundry.Casting.addRecipe(<minecraft:stone>, <liquid:stone> * 72, <foundry:mold:4>);

**Comment by davqvist** [comment]
I noticed that already and it will be fixed in tomorrow's update 1.1.0
Thanks for reporting
