### ISSUE TITLE
[Environmental Tech] Crystal Lens not working

### ISSUE THREAD

**Issue by MorganSimic** [davqvist/Exoria#257]
The Crystal Lens should increase the yield of ET Crytals like Litherite etc. At the moment this isn't the case because there is an error in the config for the void miners.

The solution is simple. In the void miner json files the entries for the crystals have to be changed from "target: whatever" to "target: crystal". This fixes the issue. It has to be done for every crystal type in every tier.

**Comment by davqvist** [comment]
Thanks, I didn't know. It says "target": "litherite" etc like it was the default before.

**Comment by davqvist** [comment]
Fixed in 1.2.0
