### ISSUE TITLE
[1.1.0] Ardite Ore Dust missing recipe

### ISSUE THREAD

**Issue by SjetCraft** [davqvist/Exoria#258]
Ardite Ore Dust is missing a Redstone Furnace/Induction Smelter recipe. (Also missing from the Melting Crucible) 
It only allows you to alloy it with Cobalt to get Manullyn.
The only valid recipes to turn it back into ingots is using Pyrotheum Dust, Magma Crucible and the Immersive Engineering Arc Furnace.

**Comment by davqvist** [comment]
Added Redstone Furnace recipe in 1.2.0
