### ISSUE TITLE
[1.1.0] Spider Eyes - Botania Rune Recipe Problem

### ISSUE THREAD

**Issue by SjetCraft** [davqvist/Exoria#259]
Since spider eyes are unavailable up to the Misty World, the Botania Rune of Autumn is uncraftable rendering a portion of Botania unobtainable.

Recipe suggestion, replace/add new recipe with a Poisonous Potato.

**Comment by GrownUpBaby** [comment]
where did you find spider eyes in the Misty World? I am trying to get them but I havent found a source yet

**Comment by davqvist** [comment]
With Woot

**Comment by davqvist** [comment]
Fixed in 1.2.0
