### ISSUE TITLE
(enchantment / sugestion) request to add a player simulator?

### ISSUE THREAD

**Issue by NerdySpider** [davqvist/Exoria#262]
### Hello.
I was wondering. it is possible if maybe we could get a mod which adds a block that right clicks, etc. It can help people automate some things? for instance. right now I'm up to progressing with astral sorcery. and I have a small collection of rock crystals that I don't need. so I tried to use multiple ways I could think of to automate the inserting of rock crystals into a lightwell. though they don't work.

###why cant I use a itemduct/hopper/etc to put one into a lightwell?

well this is because they have a different inventory. its almost like a item frame. you cant get a hopper to put a item into a hopper, so this acts the same as that. though it only inserts the item if they player clicks on it. just like a item frame. so. is there anyway if we could get a mod added that adds a player simulator? (extra utilities, cyclic. etc)

**Comment by davqvist** [comment]
I wish there is a small mod that adds that, there is even an issue made by me somewhere buried in this issue tracker,, but I am not willing to add big mods like Cyclic or Extra Utilities that change the total mod landscape just to have a block like this, sorry.
