### ISSUE TITLE
Issue creating Caminite Ring

### ISSUE THREAD

**Issue by WindFox** [davqvist/Exoria#264]
I made a reservoir from Embers and came to discover that I needed a Caminite Ring to actually use it. JEI only showed me that it needed to caminite bricks  but that's not true....apparently.

After looking online, I found out it needed 6 caminite walls as well. (This is my first time messing with Embers.)

Personally, I added the recipe into crafttweaker to fix this after checking if the recipe was modified (it wasn't).

Just thought to pass this along.

**Comment by davqvist** [comment]
Sorry for the late answer, but I am not sure I understand the issue.

**Comment by WindFox** [comment]
Don't worry about the delay. I just did a quick test and it's more of an issue with either Embers or JEI.

Either way, the recipe is messed up and doesn't show the caminite walls that are needed in JEI, but when the walls are manually placed in the crafting grid it works.

It's more of a display issue that can be fixed with craftweaker. Now that I think about it; I'm not really sure if really that much of an issue. I mean, it's an early tank (Whenever Embers becomes available) but it's such a pain to work with and not as great as an IE tank or the one from Pressure Pipes. It does have an reduced Iron cost though.

**Comment by davqvist** [comment]
Closing this
