### ISSUE TITLE
Thermal Expansion sawmill makes chopping blocks with vanilla wood logs instead of planks

### ISSUE THREAD

**Issue by querns** [davqvist/Exoria#265]
![image](https://user-images.githubusercontent.com/33518699/40887661-94d61810-6711-11e8-8e0d-5cd57412b815.png)

It's a fairly trivial thing, but it would be nice if the powered sawmill could make 8 planks like the fuel-fired Survivalist sawmill. Woods from mods like Forestry seem to be properly making planks.

**Comment by davqvist** [comment]
I will change it in 1.2.0 but to 6 planks like the other Sawmill recipes, changing all the recipes to 8 is too much work.
