### ISSUE TITLE
Paper cup/cone have the same recipe

### ISSUE THREAD

**Issue by ZeroLyfe** [davqvist/Exoria#271]
The Paper Cup from the XL Food Mod and the Paper Cone from Actually Additions have the same recipe. The Paper Cup is the default craft result though and this makes it impossible to craft the food from Actually Additions that us the Paper Cone.

**Comment by thaimichael** [comment]
I was just about to report this is something that changed with the latest update 1.1.0 it was craftable previously since I currently have 14 of them.

**Comment by davqvist** [comment]
Resolved in 1.2.0
