### ISSUE TITLE
Last Quest (Spoilers)

### ISSUE THREAD

**Issue by mkleiman312** [davqvist/Exoria#272]
You complete the last element of the "Xia" quest merely by finishing phase 1 of the Xia fight. Presumably BetterQuesting thinks that counts as "killing" Xia even though the more difficult phases are yet to come.  Maybe that's intended, and maybe its not a big issue, but it surprised me.

An alternative would be to delay completion of the quest until the player holds the Quori Fragment (voidcraft:quorifragment) which is only possible after completion of the full Xia battle.

**Comment by davqvist** [comment]
Fixed in 1.2.0
