### ISSUE TITLE
Flexible tools with the Mending upgrade reset their use status when they repair.

### ISSUE THREAD

**Issue by jman2050** [davqvist/Exoria#275]
This is for an axpickvel with the RF power upgrade. Not sure if it affects tools without the power upgrade, but it stands to assume other tools in general would be affected.

What happens is that if you have the tool in hand, every time it does an autorepair it "resets" itself in your hand (you can even see the equip animation repeat  in your hand when it happens) which cancels any mining progress you currently have on a block. Not really noticeable if you're just clearing away ash or cobble but with, say, obsidian, you very often gets reset to 0% progress as the mining gets interrupted by the repair.

**Comment by davqvist** [comment]
Seems to be fixed in 1.3.0
