### ISSUE TITLE
Can't craft sieve

### ISSUE THREAD

**Issue by coledracon** [davqvist/Exoria#279]
Sieve won't craft when using crafting table. The sieve disappears when clicking on it when trying to craft it.

**Comment by pinoytheboy** [comment]
Question: Are you using a UI crafting table or the beginner crafting table?

**Comment by davqvist** [comment]
This is duplicate to https://github.com/davqvist/Exoria/issues/200

You have to use the Tinker's Crafting Station which you unlock very shortly after.
