### ISSUE TITLE
Issue with icon for the flexible sword

### ISSUE THREAD

**Issue by Martenaizor** [davqvist/Exoria#282]
I don't think the flexible sword should look like a machine from advanced rocketry.
![bug flexible sword](https://user-images.githubusercontent.com/20764551/41201149-bec11700-6cb2-11e8-954b-e8d81dec2ec4.png)

**Comment by davqvist** [comment]
Duplicate to https://github.com/davqvist/Exoria/issues/122

Sword works normally though, it is just a texture issue
