### ISSUE TITLE
Bee genes are almost all the same

### ISSUE THREAD

**Issue by McFrugal** [davqvist/Exoria#284]
Almost every bee has "Shortest" lifespan, which might be good for mutation but is annoying when trying to get combs as they tend to die before producing anything since almost everything has "Slowest" production.  "Shorter" is available fairly easily and lets your bees last twice as long, which is better for a production line geneset.  Even ONE bee with "Normal" or longer lifespan would be quite welcome, and it seems anything faster than "Slowest" production is restricted to endgame bees.  Why is that?  Do the bees before then really need to be so slow?

**Comment by McFrugal** [comment]
Oh, I forgot the biggest problem.  All the bees you initially get have 2 fertility.  This makes genetic manipulation much more difficult than it normally is.  I'm not sure how much further I have to mutate bees to get 3 or 4 fertility, because there's no way for me to find out via JEI.  If you haven't included any bees with a higher fertility stat I strongly recommend changing that.

**Comment by davqvist** [comment]
Almost every bee has "Shortest" lifespan as a favour. For breeding it is the best and for production it doesn't matter as you will automate it (and you should as well). There will be bees with 3 fertility in the end game. 

The only thing I can admit is production. The reasoning behind not allowing Fast production was Gendustry Production Upgrades makes it quite ridiculous, but I guess in the update I can change some mutations to allow Fast

**Comment by McFrugal** [comment]
Well, with the more efficient apiary recipe you get later on I agree shortest lifespan isn't as much of a problem.  At the very beginning, however, you're probably puttering along with mass bee houses since seed oil is the limiting factor, and automated Apiaries without frames are still quite slow in small quantities.  It's annoying to constantly rebreed the princesses in bee houses to get combs so you can fuel your analyzer.

I just found a bee with Faster production in the current patch.  Silver Bees.  I'll be breeding towards that for sure, but I'll just point out that Slower production is twice as fast as Slowest, so why not include that somewhere that you can breed to in the first dimension, or Underground at the latest?  I'm not sure Underground is useful for anything other than Rock bees though.

**Comment by davqvist** [comment]
I like it how it is now, will not change anything, sorry
