### ISSUE TITLE
Manasteel Grafter not craftable

### ISSUE THREAD

**Issue by McRayJason** [davqvist/Exoria#287]
Cannot craft Manasteel grafter, because it has a same recipe as Manasteel builders wand.
Recipe conflict.

**Comment by romanticjo** [comment]
you can access the recipe using a forestry worktable.
![2018-06-13_19 58 05](https://user-images.githubusercontent.com/14045560/41389185-2d916106-6f44-11e8-9c48-59ecc110bb1f.png)

**Comment by davqvist** [comment]
Resolved in 1.2.0
