### ISSUE TITLE
Greenhouse does nothing

### ISSUE THREAD

**Issue by McFrugal** [davqvist/Exoria#288]
You can set up the multiblock just fine, and it recognizes an enclosure, but even after giving it power and placing the climate blocks then setting a temperature/humidity nothing happens.  It doesn't drain power either, so it's not trying to change the climate.

**Comment by McFrugal** [comment]
Okay I just discovered gendustry is available by the time you can make the greenhouse blocks, so it's completely useless.  I'd suggest disabling its recipes since it doesn't work.

**Comment by davqvist** [comment]
Yeah I think it is WIP in 1.12. I will disable it in 1.2.0
