### ISSUE TITLE
Habitat Locator is broken

### ISSUE THREAD

**Issue by McFrugal** [davqvist/Exoria#289]
The habitat locator points towards where biomes would be if vanilla worldgen were active.  It's useless.

**Comment by davqvist** [comment]
In which dimension?

**Comment by McFrugal** [comment]
Exoria.  It pointed out somewhere, I followed it, presumably reached the destination and it started spinning wildly and didn't stop when I went back to base.  In Misty World it pointed off somewhere that was behind a poison mist chasm so I didn't reach the destination, but it seemed unlikely for the biome to exist so I figured the same thing was happening.  Maybe I jumped the gun there though.

**Comment by davqvist** [comment]
Removed Habitat Locator in 1.3.0, use Nature's Compass instead
