### ISSUE TITLE
Forestry saplings not working in Crucible to get water

### ISSUE THREAD

**Issue by McRayJason** [davqvist/Exoria#294]
You can use vanilla saplings to get water in Crucible, but when you cannot with Forestry Saplings.

Script fix:
```
var saplings = <ore:treeSapling> as crafttweaker.oredict.IOreDictEntry;
for item in saplings.items{
    mods.skyresources.crucible.addRecipe(<liquid:water> * 250, item);
}
```
And remove the line for vanilla saplings above the leaves script, since it is covered by this

**Comment by davqvist** [comment]
Implemented in 1.2.1
