### ISSUE TITLE
Forestry blocks cause inventory desync in 1.20

### ISSUE THREAD

**Issue by McFrugal** [davqvist/Exoria#295]
Moving an item in your inventory then opening (or closing) the interface of any Forestry block will cause your inventory to desync and move the item back to where it was.

EDIT: inaccurate, see latest post

**Comment by McFrugal** [comment]
Sorry about all the edits, this was hard to nail down.  Of note is that the effect lingers, and may cause another desync when you open the UI to some other block.  It only reliably happens with Forestry blocks.

**Comment by McFrugal** [comment]
Opening and closing your inventory after interacting with a Forestry block seems to clear up the desync.  I'm guessing the GUI for Forestry blocks doesn't clear itself properly when you close them?

Thinking about it further, it's probably that your player is in some invalid state after closing the Forestry GUI, where the server thinks you can't open your inventory only close it.  So if you open your inventory in this state, anything you do clientside is reverted when you next do something that causes you to open your inventory again, because the server didn't think you should have been able to move around items.  If you open then close your inventory, the server gets the "close inventory" command and the player's invalid state is corrected, which lets you move items around next time you open your inventory.
This is without looking at the source code though, maybe it works differently.  In fact, since you can freely interact with several forestry machines in a row without a revert, it must be a bit more complicated than that.

**Comment by McFrugal** [comment]
Argh, okay, there are still some inaccuracies with what I said above.  The exact nature of the glitch is as follows:
To trigger the glitch, open a Forestry block or use the Portable Analyzer or presumably do anything that causes Forestry to start looking at your inventory.
Once you close the interface for the Forestry block, your inventory will be in a glitched state where you can move items to and from it and other containers but moving items to/from your hotbar or attempting to drop items will not work and will cause a desync instead.  For instance, if you open your inventory after taking some bees out of an apiary, pressing q while hovering over the bee will cause the icon to disappear but the item will not drop.  If you have a sign in your main inventory then shift-click it to move it to your hotbar, attempting to place it will not work.  If you simply move an item from one spot to another in the main inventory section, the move will revert when you click on that item.
Opening then closing your inventory will clear this glitched state, assuming you haven't triggered a desync.   Often this will cause the player to briefly lower whatever tool you're holding.  If your inventory is desynced, you can fix that by clicking on the malfunctioning slot/item.
Also it seems that opening a second Forestry block/item interface will temporarily suspend the glitched state and avoid a desync from moving items, as I have yet to encounter a problem when doing nothing but interacting with Apiaries and the Portable Analyzer.

**Comment by McFrugal** [comment]
This seems to be fixed in 1.3.0!

**Comment by davqvist** [comment]
Thanks for reminding me, wanted to test this, but forgot
