### ISSUE TITLE
Suggestion: recipe to turn minecraft torches into primalcore lit torches

### ISSUE THREAD

**Issue by McFrugal** [davqvist/Exoria#298]
There's various recipes to make vanilla torches, but they don't stack with primalcore torches so it causes some inventory issues.  A way to resolve this would be great.

Alternatively, those recipes could be changed to craft primalcore torches directly, but you can also get vanilla torches by shift-right-clicking a torch to pick it up.  Usually you'd do this to immediately put it back down somewhere else so it's not a big deal.

**Comment by An-Sar** [comment]
primal has recently been updated such that you should aways get the vanilla item and place the primal block.

reference: https://github.com/An-Sar/PrimalCore/issues/87

**Comment by davqvist** [comment]
Fixed in 1.3.0
