### ISSUE TITLE
Unable to cast Iron Rods

### ISSUE THREAD

**Issue by pterodactal666** [davqvist/Exoria#300]
Version: 1.2.0

Unable to cast Iron Rods in the Foundry metal caster. The Rod Casting Table works.

![2018-06-17_13 25 31](https://user-images.githubusercontent.com/7901609/41504815-bbda473c-7239-11e8-8d3c-002a87d55b79.png)

**Comment by davqvist** [comment]
I just uploaded 1.2.1 a few minutes ago which fixes this issue
