### ISSUE TITLE
Glass abuse.

### ISSUE THREAD

**Issue by UMTTEPATOP** [davqvist/Exoria#302]
When i broke normal glass block with hands i got 4 glass shards (u can get 3-4 from 1 glass block). Then i was searching in NEI with question "What can i do with these shards?", and then i found that these shards can be molten into 375 mb of glass. If i get 3 shards from glass with 100% and then i melt it in melting crucible, i get 1125 mb of glass. So, im using 1000 mb of glass, getting 1125 mb of glass. I hope you understood. P.S. You can craft normal glass with 1 clear glass (Tinker`s construct mod).
Thank you.

**Comment by McFrugal** [comment]
Is there any way to automate this?  With a block breaker perhaps?

**Comment by davqvist** [comment]
You should be able to automate it, but I will fix in the next version.

**Comment by davqvist** [comment]
Will be fixed in 1.3.0
