### ISSUE TITLE
PrimalCore isn`t working.

### ISSUE THREAD

**Issue by UMTTEPATOP** [davqvist/Exoria#303]
When i finally got the diamond. I tried to make flaked diamond by hitting it to the stone under my feet. I was hitting with full charge, very fast, was rejoining world, tried it in another world, but it didnt worked. The only way i found is /gm 1 (with pressing open to Lan and allowing cheats). P.S. There is same thing with making Flaked diamond point from Flaked diamond.
Thank you.

**Comment by davqvist** [comment]
Keep in mind that there is randomness involved. Flaking can result in the loss of the Diamond, there is that chance. Are you sure it happens every time?

**Comment by McFrugal** [comment]
You have to flake diamond on obsidian!

**Comment by UMTTEPATOP** [comment]
@McFrugal Thank You mate. @davqvist it would be really nice to write about that or give a little hint how to do it. (into quest)

**Comment by davqvist** [comment]
It is already in the quest. That is why I haven't thought of this being the issue. You have to read properly
