### ISSUE TITLE
Submitting chinese localization files for better questing etc.

### ISSUE THREAD

**Issue by misterplus** [davqvist/Exoria#305]
Hello Davqvist!

I really enjoy this modpack so I decide to make a chinese localization file for it! 

This included a localized betterquesting JSON file, some craftTweaker scripts(item rename), MPUtils' welcome message, and a modified version of the big image(that says Exoria) showed on the quest book(I added a line below that says Exoria in chinese).

I know that there's a way to make a multilanguage version bq JSON file, but it may completely change your original quest file, so I decided to make a standalone one for chinese players.

I've included all the files in a zip file(including a self-extracting archive file and some instructions on how to install the files). I've uploaded it to a cloud storage website in China.

It would be great if you can add this  to the modpack description page:

“简体中文汉化文件：https://www.bilibili.com/read/cv610943/ ”

(The download link for the zip file)

Everytime the modpack updates, I'll update the localization files as well, you don't have to worry about that.

And again, it's just a localization file for the modpack, nothing else, I'm not making any money off this and I just want to share.

A friendly chinese minecraft player,

Mike

**Comment by davqvist** [comment]
Thanks for this. Added
