### ISSUE TITLE
Immersive Engineering Blueprints

### ISSUE THREAD

**Issue by MorganSimic** [davqvist/Exoria#306]
It would be nice if there was a way of obtaining blueprints apart from the ones you get from quests. Primarly because you need blueprints for the automated workbench. The quests even leads you this way but to fully automate the crafting of circuit boards you need at least two blueprints. One for each automated workbench because they can only work on one specified thing. Other thing would be if you lose one of them you can't get them back.
Possible easy solution would be to add a recipe to copy already existing blueprints.

I don't know if a way already exists to obtain the blueprints for the arcfurnace electrodes, if not it would be nice to have a way to get those.

**Comment by davqvist** [comment]
Enabled the recipes in 1.3.0
