### ISSUE TITLE
Can`t place the Ember Bore.

### ISSUE THREAD

**Issue by UMTTEPATOP** [davqvist/Exoria#307]
When i came to the quest "booooooring" i understood that travel into exoria underground will be necessary. The 3rd and 4th pages of quest. There i should make Mechanical core and Ember Bore. How i understood ember bore should be placed on bedrock and that it needs some fuel. Then i made some pipes to put the fuel into and get the ember out, but oh no! I cant place it in Exoria Underground, it`s even isn`t writing anything like in Standart "Exoria" world. (Like "This block should be placed in Exoria Undergrounds"). I tried to place it on bedrock, any other block, on Mechanical Core, restarted world, tried to place it in other world where the mode was "Creative", i even tried to place it on another bedrock blocks, i changed the place where i wanted to place it. But, nothing helped.
And what means (DIMID: 1101)? (link for screenshot below)
https://user-images.githubusercontent.com/40309271/41564922-361d42f0-735d-11e8-94bb-ce23315b8556.jpg
Thank you.

**Comment by misterplus** [comment]
You have to place it in the Exoria underground DIMENSION.
(You have to build a portal with rune stone, check ur quest for more info.)

**Comment by UMTTEPATOP** [comment]
@misterplus i tried to place it in Exoria Underground Dimension (created portal before) but nothing happened.

**Comment by PrincessOfEvil** [comment]
The bore is pretty big and needs space

**Comment by UMTTEPATOP** [comment]
Thank you, laz2727. 
Im closing this issue.
