### ISSUE TITLE
Quest "Above the Void" not detecting quest item

### ISSUE THREAD

**Issue by querns** [davqvist/Exoria#309]
In the "Taking the long way home" quest section, the quest "Above the Void" requires a potion of plenum. However, the quest is not accepting the potion I crafted.

Looking into the matter, it appears that the NBT data on the item I crafted and the NBT data expected from the quest don't match.

The potion I made:
![image](https://user-images.githubusercontent.com/33518699/41661253-de898dd4-7463-11e8-961a-2fff3259a1d6.png)

The quest requires:
![image](https://user-images.githubusercontent.com/33518699/41661292-f7c45266-7463-11e8-8c2f-496d757968a2.png)

Changing the quest to accept an item without the NBT data `astralsorcery:{}` will likely solve the issue.

**Comment by davqvist** [comment]
I fixed this in 1.2.0, on which version are you and have you reloaded the quests since then?

**Comment by querns** [comment]
Ah, yep, I was in 1.2.0 but had neglected to reload quests. It's fixed; sorry about that!
