### ISSUE TITLE
In-World Flaking

### ISSUE THREAD

**Issue by mtimyself** [davqvist/Exoria#312]
Was looking for info on why the flaking does not seem to work as described in JEI and stumbled upon this:
https://github.com/davqvist/Exoria/issues/139
Something seem to have changed since then since there still is a chance to lose an item entirely but the drop rate is reduced to a single one (for Diamond) and not 3 or up to 3 as shown in JEI.
The loss chance, max of 1 per operation and the custom item drop mod make flaking an absolute pain right now.
In order to get 8 flaked points for the diamond mesh you can easily spend 12 diamonds and you need to go looking all over the place for them.

**Comment by davqvist** [comment]
It is entirely random, you can get 0, you can get 3. I didn't update PrimalCore in quite some time, so I know nothing has changed.

**Comment by mtimyself** [comment]
I have yet to get anything more than a single flaked diamond per operation and I have smashed a stack of them. I am not sure it is working as intended.

**Comment by McFrugal** [comment]
I've noticed they sometimes bounce way far away from you.  It's possible you're losing flakes that way.

**Comment by mtimyself** [comment]
As I said I am aware that the mod that modifies the way items drop odes not help either.
But if you can get 0-3 drops (with equal chance) you should end up with 1.5x of what you started with on average. This is absolutely not the case.

**Comment by davqvist** [comment]
It is not 0-3 drops with equal chance. It is a percentage (I think 45%) with 3 rolls.
