### ISSUE TITLE
flexible axepickvel 

### ISSUE THREAD

**Issue by ferrium42** [davqvist/Exoria#313]
I´ve finished building me a flux suit with the flux infused jetplate and the the flexible tool stops working normal. without any rf upgrade the chestplate starts to charge the tool (can be stoped when use the rf upgrade) but it can´t break anything - progress is fast but no effect i´ts just a loop and i tryed with all the flexible tools just the same

**Comment by davqvist** [comment]
Sorry for the late answer, but you can partially fix this by disabling the Charge feature of the Jetplate by keybinds

**Comment by davqvist** [comment]
Will be fixed in 1.3.0
