### ISSUE TITLE
Sealed room

### ISSUE THREAD

**Issue by Aessilva** [davqvist/Exoria#316]
a closed room is registering as unclosed no matter how many blocks i replace unless i divide the room in 2.

**Comment by redcatone** [comment]
The rooms have a limit of 10 thousand blocks for volume. Is your room extremely massive?

**Comment by Aessilva** [comment]
THAT would be why oh thank gods for the info we couldnt figure it out for nothing. is there a way to divide it with pipes still going between the 2 rooms? doors dont seem to keep a room as 'one' room

**Comment by redcatone** [comment]
Closed doors should count as a solid block. You could pipe to an inventory that's considered a solid block, like a chest, then on the other side extract from that inventory. Not the most elegant solution but it should work.

**Comment by PlacidK** [comment]
The thermal... pipe covers can 'close' a room.
