### ISSUE TITLE
Endgame Condenser shortcuts?

### ISSUE THREAD

**Issue by McFrugal** [davqvist/Exoria#317]
I noticed you can make an End Stone Condenser immediately upon getting Thermal Expansion machines as the fluid transposer has an end stone recipe.  The matching casing looks solidly locked behind access to The End, however, since it requires Purpur which requires chorus fruit.
The Enderium Condenser looks like it would take a little longer as you have to wait for a void miner to dig up some platinum.  However, the Casing can also be made as soon as you get platinum.

Is it intended for the End Stone Casing to be harder to get than the Enderium one, and the End Stone Condenser to be easier?

**Comment by davqvist** [comment]
The Endstone Casing and Condenser wasn't initially designed to be obtainable at all (until very late) but it is fine that you can make it.
