### ISSUE TITLE
Game Crash - No Crash Report Generated - Need Help

### ISSUE THREAD

**Issue by alio314** [davqvist/Exoria#323]
Please help. My game just crashed and there was no crash report generated. My game loads correctly and I get to the screen where I click on "Play Selected World." World starts to load and then I get knocked out to the error message, "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience." Any help on this would be appreciated. I Iove this game and crashed just dinking around my base. I have video if interested. Not sure if it's too big to attach here.

**Comment by davqvist** [comment]
Well without any crash log, there is not much I can help. Just making sure: There is nothing in your crash-reports folder?

**Comment by alio314** [comment]
Thanks for the quick response. The last report I see is from June 26.

https://pastebin.com/CD2UYvrZ

**Comment by davqvist** [comment]
Then I have no idea. Maybe try to describe what you did last before the crash?

**Comment by alio314** [comment]
I was running Embers pipes to my base from the resource miner and was just about to attach the pipe to a chest. My screen froze and I had to shut down my laptop. I restarted and tried to reload the game (launching from Twitch). Have tried a few times to start up, but keep getting that crash report. I would really hate to start over. Any suggestions or anyone you can put me in touch with to troubleshoot?

**Comment by alio314** [comment]
Also, I've allocated 6MB to the game and wasn't running anything else on the laptop at the time.

**Comment by davqvist** [comment]
I'm clueless, but you don't need to start over. You can load a backup that is at most 2h of gameplay lost.

**Comment by alio314** [comment]
I can't believe I've stumped you! LOL, I wish I hadn't. 

OK, I'm a newb. Do you have instructions for loading a backup? I could Google, but would appreciate seeing what you recommend.

Thanks so much,

Alison

**Comment by davqvist** [comment]
You just extract the latest zip file in your backups folder into your saves folder.

**Comment by alio314** [comment]
Thanks. That worked. I love your mods. Keep up the good work.
