### ISSUE TITLE
Flaking

### ISSUE THREAD

**Issue by mcDunni** [davqvist/Exoria#329]
Flaking = bullshit at this momment. Jei show's 4 obsidian in first try u get 0 or 4 then Jei start show 1 to 1 and u always will get 1 or 0 same whit Gem's show 3 in first try 3 or 0 then again hei start to show 1 or 0 wtf i did spend for 9 sieve's 80 diamonds i think its a  huge bug....

**Comment by davqvist** [comment]
It is not a bug, it is just not transparent displayed. You can get 0-X and JEI shows one random number between 0 and X. I already informed the mod dev and he will change it. 80 Diamonds for 9 Sieves seems about right maybe a tiny bit unlucky.

**Comment by McFrugal** [comment]
I never bothered making more than one diamond sieve.  Just automate it with the auto-sifter and put a ton of wheels on the axle.  Each wheel makes the sifter work faster.
