### ISSUE TITLE
Trowel for bait duplicate recipe.

### ISSUE THREAD

**Issue by CypSteel** [davqvist/Exoria#330]
Thanks for the pack!  Having a blast and playing with mods I don't normally see.

I was looking to get bait for my water strainers to increase their efficiency.  When you go to make the garden trowel from Water Strainers mod, it makes the iron trowel from Binnie's Botany.

Not sure if this is working as intended.

**Comment by davqvist** [comment]
Thanks for reporting, I will fix in next update. But the bait is not to increase efficiency, it is for the Fisherman's Strainer, just fyi

**Comment by davqvist** [comment]
As the Fisherman's Strainer is disabled I will disable the Trowel as well as it is useless in 1.3.0
