### ISSUE TITLE
Sword from flexible tools looks like space drill form advanced rocketry.

### ISSUE THREAD

**Issue by Androidonator** [davqvist/Exoria#331]
Fuctions as sword but this really grinds my gears since I can't fix it anyway.

**Comment by Androidonator** [comment]
I am now trying to change resource of block from advanced rocketry to that of flexible swords using resource pack but that wouldn't fix anything.

**Comment by Androidonator** [comment]
Also i now tried updating flexible tools but nothing changed.

**Comment by davqvist** [comment]
Duplicate of https://github.com/davqvist/Exoria/issues/122
Nothing I can do unfortunately atm
