### ISSUE TITLE
Unable to craft sieve

### ISSUE THREAD

**Issue by sybaik1** [davqvist/Exoria#337]
i have the sieving_knowledge stage and the questbook wants me to make a sieve but when i place the recipe on the crafting table nothing appears, also when i go to JEI and find sieve and click the + the crafting table seems to work but when i click the sieve that has appeared it just disappear.

**Comment by davqvist** [comment]
Due to a bug you need to use the Tinkers Crafting Station which you should already have unlocked or unlock shortly. This is a Duplicate of https://github.com/davqvist/Exoria/issues/200
