### ISSUE TITLE
Knowledge unlock does not unlock crafting recipe.

### ISSUE THREAD

**Issue by OfficerLovejoy** [davqvist/Exoria#340]
I cannot progress to new knowlegde like the sieve or crafting station even though i unlocked the quests.
The recipees are not working for me, even when i shift click them in through the ?. I can see the sieve as the result but when i click on it, it disappears and no crafting takes place.
If i just put the materials in, i don't see the sieve at all.
I tried updating my quests through the checkbox quest on page 1 - no change.
Using version 1.2.1 solo, so no server.

**Comment by davqvist** [comment]
You need the Tinkers Crafting Station which you unlock shortly due to a bug which itself will be fixed with today's planned update
