### ISSUE TITLE
[Minor Issue] Powered Thingies Machines

### ISSUE THREAD

**Issue by MorganSimic** [davqvist/Exoria#342]
There are some Powered Thingies machines that are not craftable due to needing vanilla tools. Namely the "Crop Cloner" - basically a garden cloches -, the "Electronic Butcher" - kills animals for drops - and the "Crop Farmer" - does what you think - and the "Farmer Machine" - i have no idea what that thing does.
They and the other machines overlap mostly with Industrial Foregoing in termns of functionality and casing cost, so they could maybe be disabled and hidden or the recipe needs changing.
And the Fluid Compound Producer and Item Compound Producer do nothing in this pack. So they could be removed. Same with ore lumps if you want to be thorough.

**Comment by davqvist** [comment]
Fixed in 1.3.0c although I didn't disable the Item Compound Producer as it possibly can be used to make Stone from Cobble and Lava
