### ISSUE TITLE
Crafting diamond tools requires lacquer stiks

### ISSUE THREAD

**Issue by leisuretime1** [davqvist/Exoria#344]
After latest update now diamond tools require lacquer sticks.  Was this intentional, b/c I can't find resins to do so.

**Comment by davqvist** [comment]
No, this was not intentional. A mod update must have caused this. Sorry. Will fix shortly.

**Comment by leisuretime1** [comment]
cool cool!

**Comment by davqvist** [comment]
Fixed in 1.3.0c
