### ISSUE TITLE
Immersive Engineering Automated Workbench not formable

### ISSUE THREAD

**Issue by wsetzer** [davqvist/Exoria#351]
In the "Powering Up" tab, in the "Automating Components" quest, I built the pieces, but when trying to click the resulting multiblock, I get the error: You cannot form this Multiblock!  Further Progression is Required!  I assumed I had the proper progression, since the quest was open.  This happened in v1.2.1 and v.1.3.0c and I did reload the quests (a couple times) to make sure there weren't any missing quest progressions.

**Comment by davqvist** [comment]
The error message is misleading, you just built the structure wrong or click on the incorrect block. Make sure the conveyors go in the right direction for example.

**Comment by wsetzer** [comment]
Oops, you are correct.  I thought I had clicked on every block, but I never clicked on the slabs, apparently.  Sorry for the incorrect report.
