### ISSUE TITLE
Ae2 meterors are spawning way too frequently in the overworld

### ISSUE THREAD

**Issue by Trinsdar** [davqvist/Exoria#369]
I noticed that when I went to the overworld in my creative test world ae2 meteors were spawning everywhere. they should be either turned down or perhaps even turned off as they have no use.
![2018-08-10_21 18 29](https://user-images.githubusercontent.com/30245301/43986681-a1a90c76-9ce2-11e8-9b58-425bbe495d4a.png)

**Comment by davqvist** [comment]
This is intentional as you will see in the quest line
