### ISSUE TITLE
crash during loading

### ISSUE THREAD

**Issue by AbonimableBubblegum** [davqvist/Exoria#373]
I was playing the pack last night and started down the quest that has you make an incubator and enzyme and everything was fine. Tried to open the pack today and had it crash on loading with the following message. 

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GenDustry (gendustry)

Tried a different version of the pack and still could not open it. I tried installing an older version of gendustry but still got the crash. I then removed the gendustry mod  and could open the pack. Here is the crash report https://pastebin.com/nLZQf0xv

**Comment by davqvist** [comment]
I know of that issue, it happened overnight. The easiest way to fix this right now is to use the jar launcher not the native launcher which uses a newer Java version. You can change that in the Twitch Launcher Minecraft settings.

**Comment by superhealing** [comment]
happened me too but i use multimc5 :/ 
let me explain, i played a day ago worked 100% no problem, but if i press play, i get same problem with user have up..

**Comment by AbonimableBubblegum** [comment]
Thanks davqvist that worked for me, hope it works for other people too

**Comment by davqvist** [comment]
@DragonHacker1 Not sure where to do it on MultiMC, but you need the jar launcher, not the native launcher because the native launcher uses an older Java version. Reason still unknown I believe. Many say it is because the Windows Update of yesterday but some Linux users have the same problem.

**Comment by davqvist** [comment]
Checking now, it seems to be not because a Windows Update, rather a thing Mojang messed up and they apparently fixed it, so the old method of launching should work again. I am closing this issue now, feel free to post here if it is still broken and I reopen it.
