### ISSUE TITLE
Exoria Underground portal spawned me above bedrock layer

### ISSUE THREAD

**Issue by ChillyFierce** [davqvist/Exoria#374]
When i tried to use portal server lagged and i went main menu reload game i was above bedrock. Which file should i delete in save folder in order to reset this dimension?

**Comment by davqvist** [comment]
DIM1101

If it happens again, build your portal at a different position, maybe lower down in the ground.

**Comment by davqvist** [comment]
Wait portal to the Underground or from the underground?
DIM1101 - Underground
DIM1102 - Core

**Comment by ChillyFierce** [comment]
Just suicided and gave items back with console and portal was fine. Before that bug happened game was laggy i went through portal but it didn't let me in so i relogged. Now its fine thx anyway. Also shulkers feel hard to find idk if that was my luck :P
