### ISSUE TITLE
No Items from Alfheim Portal on server

### ISSUE THREAD

**Issue by Schokopizza** [davqvist/Exoria#379]
Hey there.
I am trying to play Exoria on a server with friends and first things first. I never spawn a portal if i create a world on the server. I have to create it on Single player and copy the world or rebuild it in multiplayer with creative.
But even if i do so the portal dosn't work. It does half way. It does consume the items I throw in but won't give me anything in return. Singleplayer works just fine. it only happens to the server.

**Comment by davqvist** [comment]
Not sure what to tell you, Portals spawn but you can be unlucky as there is a bug where it doesn't spawn as you can read in the introductory text when you login. Also the portal works just fine in MP. I would need more information. What kind of server did you setup? Vanilla Forge / with Sponge? Which recipe does not work? What exactly did you do?

**Comment by Schokopizza** [comment]
I am using a forge server. I looked up what forge version you have in your mod and downloaded the forge installer with the very same version. and installed a server from it. copyed mods and config folder and pasted them into the server folder. had some issues with buildcraft-compat but that was easy to solve i just removed your vompat versoin witch is xxxx14 and replaced it with xxxx15 since i had the error that the ore dictionary wasn't loaded so i got an error when trying to join the server.
it's not just that the portal isn't spawning and then not working if you join my server for the first time you don't even get the starter items. and i only tryed the 4 ashe blocks to get saplings since it is kinda nessesary to progress further. even tryed to throw in a bunch of them but i tryed throwing random stuff in and everything vanished. I rebuild it from creative. not sure if that is the reason it won't work. I could give you more detailed information on versions etc if you need them. I would love to try out other kind of server too if you tell witch and where i can find one cuz i am not that knowledgeble about minecraft server. Thanks for the help tho.

**Comment by davqvist** [comment]
You forgot the scripts and structures folder. I recommend the server download from Curseforge which is ready to install and play. That is why structures are not spawning and recipes not working.
