### ISSUE TITLE
Not sure how to progress with Metal Caster

### ISSUE THREAD

**Issue by NBMarc** [davqvist/Exoria#393]
I'm at a point where I need gears or nuggets to continue with any quest which means I have to use the metal caster. However i'm not sure how to fill the metal caster with liquid metal because you cannot make a refractory fluid container. Is there a way to transfer liquid from the crucible furnace to the metal caster?

**Comment by davqvist** [comment]
The easiest and intended way is to use the faucet that is required by the quest.

**Comment by NBMarc** [comment]
Ah I got it thankyou
