### ISSUE TITLE
VoidCraft Portal not at the given coordinates on Earth

### ISSUE THREAD

**Issue by sensualpudding** [davqvist/Exoria#396]
Just landed on Earth, went to the coordinates (x1000,z1000,y40) and there is no portal room to be found. Even went in spectator mode and looked around a 100-200 block radius and found nothing.

**Comment by davqvist** [comment]
I heard several reports of that happening. Sorry, not sure why, but you can go anywhere on earth and type "/#gen PortalRoom" to generate it. Hope that helps.

**Comment by sensualpudding** [comment]
Hi, thanks for the response! So I typed that command, and it said in chat “Operation in preview - /#confirm or /#cancel” So I typed /#confirm and nothing happened. So I tried typing in the command you gave me again and now it just says “The structure generation was canceled!” Tried restarting the game and trying again but it keeps giving me “The structure generation was canceled!”

**Comment by davqvist** [comment]
Huh, if you confirmed, there should be a small shaft going down in the room. Not sure what else to tell you.

**Comment by sensualpudding** [comment]
Went into spectator again, couldn’t find anything. I’ll try again later though. Thank you for the help nonetheless. Cheers.

**Comment by PandojoCode** [comment]
I have the same problem, it's because "generate structure" option are on "off" when you create the new world

**Comment by PandojoCode** [comment]
I found this solution to modify the option in a world already created :

1) Install and run [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases/tag/v2.7.6.-win)
2) Stop your game/server from running.
3) Create a backup of your level.dat before editing (just in case).
4) Open the level.dat for your structureless world.
5) Find the "MapFeatures" option. Change the value from 0 to 1

6) Save and lauch your world, after that you can do the command "/#gen PortalRoom" and click on "/#confirm" (however it will only work if you do the command in a chunk that has not yet been generated).

**Comment by PandojoCode** [comment]
![TkVFZDE](https://github.com/davqvist/Exoria/assets/174542992/6236750d-ed32-4853-81b9-37107c39cd03)

**Comment by davqvist** [comment]
> I have the same problem, it's because "generate structure" option are on "off" when you create the new world

That is not true. That only affects vanilla structures.

**Comment by davqvist** [comment]
> I found this solution to modify the option in a world already created :
> 
> 1. Install and run [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases/tag/v2.7.6.-win)
> 2. Stop your game/server from running.
> 3. Create a backup of your level.dat before editing (just in case).
> 4. Open the level.dat for your structureless world.
> 5. Find the "MapFeatures" option. Change the value from 0 to 1
> 6. Save and lauch your world, after that you can do the command "/#gen PortalRoom" and click on "/#confirm" (however it will only work if you do the command in a chunk that has not yet been generated).

As said above, steps 1-5 are not needed at all. It just sometimes doesn't generate because there is like a feature blocking it, like a river or so.

**Comment by PandojoCode** [comment]
I'm not saying the opposite, but the problem of "The structure generation was canceled!" is due to the option is on "off"... I had the same problem and after doing steps 1 to 5, it solved the problem (But only in a chunk that has not yet been generated)

The command "/#gen PortalRoom" don't work if "generate structure" option is on "off"

**Comment by PandojoCode** [comment]
And if we don't want another structure to be created, well we reset the option to 0 after
