### ISSUE TITLE
Vanilla Recipes still active 

### ISSUE THREAD

**Issue by K3NT3CH** [davqvist/Exoria#398]
I noticed when I came to craft a chest, that I am still able to craft with just 8 wood, and not have to use the iron nugget recipe.

<img width="459" alt="MC Chest Exoria" src="https://user-images.githubusercontent.com/59655112/71985857-4d478b80-3223-11ea-8a72-86cabc756f8b.png">

**Comment by davqvist** [comment]
Odd. How did you install it or rather where or with which launcher? Singleplayer or on a server?

**Comment by K3NT3CH** [comment]
I found it was a launcher issue, I used a too newer version of forge, once I downgraded, reinstalled the pack it worked. Thanks for your help. Amazing pack, by the way, loving it.

**Comment by davqvist** [comment]
Awesome, glad you figured it out.
