### ISSUE TITLE
tps lag

### ISSUE THREAD

**Issue by ghost** [davqvist/Exoria#401]
hi, i was playing with mi friend hosting the world on my pc, suddently after automatizing the generation of diamonds ecc from ash, i noticed a heavy tps lag, it was about 8 tps.
anyone can help me to revive my world? 
(sorry for my bad english, i'm italian)
i'll leave some screens, maybee it can be usefull
![2020-05-12_21 36 24](https://user-images.githubusercontent.com/65252397/81737612-a60c8680-9498-11ea-83ac-4aae64f53584.png)
![2020-05-12_21 33 45](https://user-images.githubusercontent.com/65252397/81737627-ac026780-9498-11ea-9d67-d03c5e67517b.png)

**Comment by davqvist** [comment]
Send me screenshots or chat transcript of what "/profile e" tells you, please

**Comment by ghost** [comment]
![2020-05-13_13 50 55](https://user-images.githubusercontent.com/65252397/81808988-e1529800-9520-11ea-8c59-964fd9eec712.png)
![2020-05-13_13 50 48](https://user-images.githubusercontent.com/65252397/81808998-e4e61f00-9520-11ea-98b6-2fc3a3c1834a.png)

**Comment by davqvist** [comment]
So the two most lag causing things are the 2 Buildcraft Wooden Engines at those coordinates in the second screenshot. Not sure why though, also an Item Extractor and a Hopper nearby, do you have a lot of items pumping through BC pipes, maybe in a loop or so? Please check those blocks at the coordinates in the second screenshot.

**Comment by ghost** [comment]
Thank you very much! you opened a world for me with this miracolous command and saved my world!
GGWP

**Comment by ghost** [comment]
i removed those blocks and replaced them with the @embers item pipes and extractors hoping to reduce lag

**Comment by ghost** [comment]
those too produce lag :(
