### ISSUE TITLE
No mobs spawning. HELP!

### ISSUE THREAD

**Issue by Kennardtalks** [davqvist/Exoria#406]
I didn't notice until I reach the underground that golems weren't spawning at all. I literally search for them from bedrock to the top level but didn't find them, I also noticed that since the beginning of my playthrough, the fairies weren't spawning either, so I created several new worlds to see if they will spawn but it didn't work. The only thing that I modified on the mod pack itself was that I added Optifine, so I wonder if that is what's causing this issue, anyway I don't have any idea of how to fix this so if I can receive any help I'll really appreciate it.

**Comment by Kennardtalks** [comment]
So I've removed Optifine and that solves the issue. I do hope Optifine should be made compatible in the future since most of the players like it because it helps a lot with the performance and also because of the zoom feature. I highly recommend solving that as well, apart from that this is indeed an awesome mod pack.

**Comment by davqvist** [comment]
Yeah it is Optifine's issue and no Optifine is not supported and won't be, sorry.
