### ISSUE TITLE
Compacting Drawer requests

### ISSUE THREAD

**Issue by zOwenn** [davqvist/Exoria#53]
Could you add the products of the dense water strainers to the compacting drawers? (Mud Balls -> Mud, Sand -> Sand, Chalk Dust -> Chalk, Terra Clay Clumps -> Block) - Thanks

**Comment by davqvist** [comment]
Added Strainer and Sieve products to Compacting Drawers in 0.1.4, let me know if you find more that need to be added.

**Comment by davqvist** [comment]
Ash to Ash Block missing

**Comment by davqvist** [comment]
Added Ash and Clay
