### ISSUE TITLE
Rebalance Sieve/Strainer percentages

### ISSUE THREAD

**Issue by davqvist** [davqvist/Exoria#57]

**Comment by davqvist** [comment]
At least increased Dust in 0.1.4

**Comment by zOwenn** [comment]
Black Quartz dust seems to be a little high at 20%

**Comment by davqvist** [comment]
Agreed. Gems will get slightly raised. Earthwax removed, Loam slightly lowered.

**Comment by davqvist** [comment]
Those seem fine now
