### ISSUE TITLE
Exception in thread "VoidCraft Contributor Loader" 

### ISSUE THREAD

**Issue by SjetCraft** [davqvist/Exoria#59]
Exception did not show in latest.log, only in MultiMC console.
Crashlog: https://paste.ee/p/e8RsU

**Comment by SjetCraft** [comment]
Had the Tiny Fluid Output GUI open of a Foundry with about a bucket of molten iron in the Output, attempted to put a bucket on the hotbar when the client froze.
Killed the client (Task Manager) after ~120 secs.

**Comment by davqvist** [comment]
Closing now as this never came up again
